### PR TITLE
feat: Tweaks and improvements

### PR DESCRIPTION
**Pull request by svvimming**
Some small fixes:

- [x] Added tab index to FAQ accordions on Public Data Awards and Public Data Commons pages
- [x] Added missing breadcrumbs site-wide
- [x] Added missing hover effects on site logo, careers CTA (get involved page) & footer in-text links
- [x] Fixed hover effect on nav in Safari (and Firefox)

### CODE REVIEW

**Review by nicole-code — CHANGES_REQUESTED** [review]
These look super awesome! Nailed it! 
Is it possible to add tab index to breadcrumbs as well @svvimming ? 

Also, this is kind of random and super specific - but for the accordions, if there are any in-text links and user is tabbing through but does not open the accordion, the in-text links are still being tabbed through (see screenshot to see what I mean!) - and that makes total sense but should that still be the case from a UX standpoint? @orvn can I ask for your opinion on this and please let me know if this is maybe going a little bit too far?

https://user-images.githubusercontent.com/67213981/190502795-870b1ac9-31bb-468f-910a-68cd5eb132ff.mov

**Comment by svvimming** [comment]
@nicole-code just added tab index to breadcrumbs. Yeah I was wondering about tabbing over accordion content when the section is closed - I think from the perspective of tab accessibility it actually makes more sense. Visually it looks a bit awkward but I don't think that will be relevant to users with screen readers/tab accessibility needs. @orvn what are your thoughts?

**Comment by nicole-code** [comment]
Hey @svvimming ! Changes looking great  :) - I'll approve once we get Orun's input about the accordion!

**Review by orvn — APPROVED** [review]
> Yeah I was wondering about tabbing over accordion content when the section is closed - I think from the perspective of tab accessibility it actually makes more sense. Visually it looks a bit awkward but I don't think that will be relevant to users with screen readers/tab accessibility needs. @orvn what are your thoughts?

Yeah, exactly, because it's a clickable area we should definitely have it in the tabindex flow (it will only look awkward for the < 1% of users who are tabbing, and that segment expects it). IMO it's normal that the heading for each accordion item has 100% width, which is shown by the focus ring.

**Pull request merged**
