### PR TITLE
feat: blog breadcrumbs

### PR DESCRIPTION
**Pull request by svvimming**
Blog & _id pages are nested under a new blog directory. The breadcrumbs and url will reflect this new structure:

URLs: /blog/<slug>
Breadcrumbs: Home / Blog / <slug> 

EDIT: the zero module has also been migrated from a dependency to the `modules` directory in the root level.

### CODE REVIEW

**Review by nicole-code — CHANGES_REQUESTED** [review]
Interesting bug ->

When I hit `/blog `and then I click on one of the cards to view a single blog post it works. But when I use the pagination to navigate through other blog posts, the breadcrumbs stay the same, the url changes to the paginated blog post but I am taken right back to blog index page.

See video to recreate the bug -

https://user-images.githubusercontent.com/67213981/204049426-b08e505f-663c-4f29-a170-1f42361c890a.mov

**Review by orvn — CHANGES_REQUESTED** [review]
There's an issue on mobile where the breadcrumbs overflow the viewport if the blog single title is long.

Solutions are either
1. Wrap to multiple lines, and increase the space between the logo and the main content
2. Truncate the field with an ellipsis on overflow (in CSS)

breadcrumb overflow

**Review by orvn — APPROVED** [review]
Lgtm now

**Review by nicole-code — APPROVED** [review]
woo! tried to break it @svvimming . I couldn't do it 😆 . 
Works reallllly well 👏🏻

**Pull request merged**
