### PR TITLE
feat: rename sections

### PR DESCRIPTION
**Pull request by nicole-code**
This PR addresses Notion ticket `FIFO-34`. This PR renames sections throughout the Filecoin Foundation site, specifically pertaining to anchor tags. URLs are now more reflective of content that the user is seeing in the viewport.

### CODE REVIEW

**Comment by orvn** [comment]
@nicole-code did you search the codebase for instances of any of the old anchors within links? (like in the nav, which I see you got, but also in other places, like within blocks of paragraphs?)

**Comment by nicole-code** [comment]
Oop - the answer is no and it completely slipped my mind, I am so sorry! No matter @orvn I'll get to it ASAP!

**Comment by nicole-code** [comment]
@orvn I only actually found one instance that I missed - it was a CTA, actually. There aren't too many internal anchor links - most links are external!

**Review by orvn — APPROVED** [review]
lgtm, will merge when I have time to do a deeper test!

**Pull request merged**
