### PR TITLE
feat: Background layers animation

### PR DESCRIPTION
**Pull request by svvimming**
The background layers component has been updated to add animation to the layers on viewport entry. At this time the PR should not be merged but should just be tested for performance. The only animations enabled for now are in the layers surrounding the filecoin logo at the beginning of the index page (see photo). The animation still needs tweaks, specifically a proper start state, but I wanted to PR now for performance testing before moving any further with implementation.

Screen Shot 2022-04-21 at 2 16 53 PM

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
Looks pretty good @svvimming! There are some tweaks needed to be able to evaluate further visually, but implementation-wise I'd say this is the right approach.

- Can we slow down the transition timing? Like twice as much duration?

- There's a weird flashing effect that occurs because the page loads with all the elements in their final state, they disappear, and then they reappear via the animation

- Can we make it such that, for some blocks, the animation is able to fire multiple times if the user scrolls back up?
  - i.e., the user sees the animation upon reaching an intersection with their scroll, but then scrolls back up, and back down to the intersection, firing the animation again

  - I say "for some blocks" because it won't work for the super large elements that span a lot of the page

**Comment by svvimming** [comment]
@orun here are the changes I made:

1. The animation duration is twice as long.
2. The animation now starts in the correct state (i.e. no layers are displaced relative to the topmost layer).
3. Animations can optionally be 'reset' by scrolling past a 'reset element' specified as a component prop in page content json files by element id. For example, currently, after triggering the first two animations at the top of the index page and then scrolling past section 2 (i.e. the DOM element with id `section_2`), returning to the top of the page will re-trigger both animations. This will happen indefinitely provided the same steps are executed.

I tried adding this animation to the huge page-long layers and the results were extremely choppy - basically just saw the initial animation state and some time later the final state, with no animating between.

**Review by orvn — CHANGES_REQUESTED** [review]
Oh nice, that looks super smooth! 

I think the next step is to get a bit of a delay in there in between each layer. Right now, it's so fluid that it looks like they're all one background being made visible. Instead, what would be best is a staggered/stepped look (which was more similar to what was there before).


layer one animates → layer one slows/eases down → break/delay → layer 2 animates ...

Right now, the break is the missing piece. We could either add in an actual break in the animation, or change the timing function to a bezier that speeds up and then slows down (or even inverts) toward the end.

By the way, this is a bezier I use a lot `cubic-bezier(0.8, 0.5, 0.2, 1.3)`. You can try it out [here](https://cubic-bezier.com/#.8,.5,.2,1.3) @svvimming.

**Comment by svvimming** [comment]
@orvn is this more what you had in mind?

**Comment by D3AS8A** [comment]
@svvimming this is great! It's a little slower than ideal, can we speed it up? Both in terms of the animation and the delay.

**Comment by svvimming** [comment]
@D3AS8A I sped it up by 50%, how does it feel now?

**Review by orvn — CHANGES_REQUESTED** [review]
> @D3AS8A I sped it up by 50%, how does it feel now?

1. @svvimming can we speed it up even more by a little?

2. I think we should disable this on mobile, the effect isn't really visible there

Other than that, this looks good to me!

**Pull request merged**
