### PR TITLE
feat: 404 page

### PR DESCRIPTION
**Pull request by svvimming**
404 page implemented in the error.vue layout with a matching IPFS 404 page in the static directory.

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
Do we have to include fonts in two locations (`assets` and `static`) to support the plain html 404? cc @timelytree

**Comment by timelytree** [comment]
Oh @orvn that is an _excellent_ question → I'd say instead let's move fonts out of `assets` and into `static`. We can just point to the `static` dir when importing fonts via Webpack, it should still work.

**Review by timelytree — CHANGES_REQUESTED** [review]
Looks great!! I've got 1 request and 1 bug fix:

1. Can you move all fonts out of `assets` and into `static` so that they only live in 1 place? We'll make this change for all new projects moving forward (and the occasional old project when needed).
2. Looks like some of the required JS isn't loading properly on the statically generated page, which is breaking things like navigation. We might need a different approach for how to generate this page *tear → more details to come via Asana

screencapture-bafybeigsgxcg5t2smtoysqssxaatbx6n3tufbo6v7v6p2v35pclsrxpabi-on-fleek-co-asd-2022-04-12-20_20_54

**Comment by svvimming** [comment]
@orvn @timelytree I might need one of you to resolve the conflicts in the package & package-lock files. Looks like some dependencies have been removed since I branched off of develop.

**Comment by orvn** [comment]
@timelytree, was this when you moved dev dependencies into regular dependencies?

**Pull request merged**
