### PR TITLE
feat: tab accessibility on nav dropdown menus

### PR DESCRIPTION
**Pull request by svvimming**
Tab accessibility for the site nav. This solution makes use of tab indexing; because dropdown contents are not children of their respective nav headings (rather they each live in a single wrapper mega menu that is a sibling of nav headings), to ensure proper tab accessibility and flow the DOM tab order had to be overridden. The contents of each dropdown menu is given a single tab index i.e. 1, 2, 3 etc that corresponds to the tab index of the nav heading to which its menu belongs.

### CODE REVIEW

**Review by nicole-code — CHANGES_REQUESTED** [review]
Woop, I'm sorry @svvimming I thought I already reviewed this buuuuut turns out I have not! Did you happen to fix the sub-nav items not working on this yet? Just on the latest build preview and it looks like the sub-nav links are working *sometimes* but not all the time - is this happening for you as well?
If I am just tabbing through the sub-nav links, they work - but if I select a link in the top-level nav, the sub-nav links no longer respond to the Enter key. Does that make sense 😬  ?

**Comment by svvimming** [comment]
@nicole-code I just pushed a fix, I think I figured out the reason behind this. Let me know

**Review by nicole-code — CHANGES_REQUESTED** [review]
Hmm - I still seem to be having the same problem which is that the sub-navs work if you're just navigating those but once you start navigating to top-level nav links, the sub-nav links are not responding to the enter key...are you having this problem on your end 😬 ?

**Comment by svvimming** [comment]
@nicole-code okay I think this is an issue with production vs development because I'm not having any issues on my local. I tried another tweak but if it doesn't work I'll have to crack this open and have a deeper look

**Comment by nicole-code** [comment]
@svvimming its still happening on my end. Weird!

**Review by orvn — CHANGES_REQUESTED** [review]
`tab` and `shift` + `tab` both work great when navigating the menus via keyboard (tested on Firefox)

@svvimming two change requests:

1. When exiting the nav via tab, close the submenu (if tabbing or focusing onto something else). For example, when you tab beyond the last item in the last nav, the nav should close because the focus is now outside the nav container
2. Can the site logo be first? i.e., its tab order would be before the nav. Currently it gets tabbed into _after_ the last nav item, which is a little backwards.

**Review by orvn — COMMENTED** [review]
@svvimming, nice, that fixed it!

Does the tabbing work for you in Safari, or does it seem erratic? Not sure if it's a config with my Safari.

@nicole-code, I tested the anchor links via tabbing quite a bit and found that they always sent me to the correct page/section, fyi

**Review by nicole-code — APPROVED** [review]
nailed it. boom 🎤 💥

**Review by orvn — APPROVED** [review]
woooot

**Pull request merged**
