### PR TITLE
feat: Button and card micro Interactions

### PR DESCRIPTION
**Pull request by svvimming**
Interactions added in this PR:

- hover states to resources sections site wide
- hover state button colours site wide
- link in text colour
- event card hover state size increase & box shadow
- navigation animation on hover

### CODE REVIEW

**Review by orvn — APPROVED** [review]
Approving, but is this the intended hover effect for buttons? @svvimming? I think it's less appealing than what was there before:

- Previous hover effect 2rvn 2021-11-18 at 16 24 49
- Updated hover effect 2rvn 2021-11-18 at 16 24 40

**Comment by svvimming** [comment]
@orvn I think I agreee, but yes this is the correct effect from [this task](https://app.asana.com/0/1198910434444850/1201296423533598) and can be seen in the XD document.

**Comment by orvn** [comment]
@emilymariahh requesting to revert to the previous effect—thoughts?

**Comment by emilymariahh** [comment]
> @emilymariahh requesting to revert to the previous effect—thoughts?

We can convert to previous effect if it doesn't look as good in context

**Review by orvn — APPROVED** [review]

**Pull request merged**
