### PR TITLE
feat: Slack Icon and link added to SocialIcons component 

### PR DESCRIPTION
**Pull request by svvimming**
This icon and link now appear in the 'Get Involved' community links in the navigation dropdown among other places in the site. Also a quick fix was added for a bug with the navigation inner border size.

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
@timelytree, does the au-nuxt-module need to be auto-incremented here? Or does the path/module name need to change?

Build error: `npm ERR! 404  'au-nuxt-module-zero@1.0.12' is not in the npm registry.`

**Comment by orvn** [comment]
@D3AS8A, should the Slack outline be an outline like the others? (rather than solid)

slack icon

**Comment by D3AS8A** [comment]
> @D3AS8A, should the Slack outline be an outline like the others? (rather than solid)
> 
> slack icon

Would Ideally be outlined :)

**Review by orvn — APPROVED** [review]
Stroked the outline and removed the fill on the Slack icon

**Pull request merged**
