### PR TITLE
feat: accessibility fixes

### PR DESCRIPTION
**Pull request by splumms**
Branch includes:
 - accessibility polish for the governance, grants, about and ecosystem pages

### CODE REVIEW

**Review by orvn — CHANGES_REQUESTED** [review]
Have a few change requests:

- For optimal contrast, can we use the color @emilymariahh mentioned for the FF site's focus outlines? (it's a yellow hue)

- Buttons don't show that they're focused when tabbing into them (in the screenshot below, I'm tabbed into the button, but its state looks the same as untabbed)
a11y-buttons

- Without altering the design, can we add a bit of padding around areas where the outline touches the element the user is tabbed into? We should have at least a few pixels, or `0.125rem` clearance (particularly for larger elements and bigger font sizes, where it's more noticeable)
  - Cards are the biggest culprits
  - In-line links look fine
  - Magellan nav sidebar links are too close on the left side

a11y-padding-2 png a11y-padding-1

@splumms 
cc @nicole-code

**Comment by nicole-code** [comment]
> Have a few change requests:
> 
> * For optimal contrast, can we use the color @emilymariahh mentioned for the FF site's focus outlines? (it's a yellow hue)
> * Buttons don't show that they're focused when tabbing into them (in the screenshot below, I'm tabbed into the button, but its state looks the same as untabbed)
> 
> a11y-buttons
> 
> * Without altering the design, can we add a bit of padding around areas where the outline touches the element the user is tabbed into? We should have at least a few pixels, or `0.125rem` clearance (particularly for larger elements and bigger font sizes, where it's more noticeable)
>   
>   * Cards are the biggest culprits
>   * In-line links look fine
>   * Magellan nav sidebar links are too close on the left side
> 
> a11y-padding-2 png a11y-padding-1
> 
> @splumms cc @nicole-code



> Have a few change requests:
> 
> * For optimal contrast, can we use the color @emilymariahh mentioned for the FF site's focus outlines? (it's a yellow hue)
> * Buttons don't show that they're focused when tabbing into them (in the screenshot below, I'm tabbed into the button, but its state looks the same as untabbed)
> 
> a11y-buttons
> 
> * Without altering the design, can we add a bit of padding around areas where the outline touches the element the user is tabbed into? We should have at least a few pixels, or `0.125rem` clearance (particularly for larger elements and bigger font sizes, where it's more noticeable)
>   
>   * Cards are the biggest culprits
>   * In-line links look fine
>   * Magellan nav sidebar links are too close on the left side
> 
> a11y-padding-2 png a11y-padding-1
> 
> @splumms cc @nicole-code

@orvn I will totally implement the new focus outline color but I am waiting for Jac to test against all backgrounds!

**Comment by nicole-code** [comment]
Also , I think the problem with the focus outline on buttons is Firefox-specific, I just noticed it myself @orvn cc @splumms

**Comment by orvn** [comment]
@nicole-code Ah, in that case, can you also re-check this, but cross browser? (only relevant for desktop browsers, so no mobile required)

**Comment by nicole-code** [comment]
@orvn for sure! I'm sorry, I assumed this was tested across browsers I definitely shouldn't have assumed that!

**Review by orvn — APPROVED** [review]
Looks great! Tested in Firefox pretty thoroughly.

**Pull request merged**
